/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Unlock Sapphire Balls': '解锁蓝宝石球',
    'Unlock Topaz Balls': '解锁黄玉球',
    'Unlock Turquoise Balls': '解锁绿松石球',
    'Upgrades\n\t\t\t\t\t\t': '升级\n\t\t\t\t\t\t',
    'Welcome to Pachinkremental!': '欢迎来到弹珠放置！',
    'Wheel Speed': '轮盘速度',
    'Your save file is below. Copy the text and keep it someplace safe.': '下面是您的保存文件。复制文本并把它放在安全的地方。',
    'source code': '源码',
    'Spin the wheel!': '转动轮盘！',
    'Stackable Buff': '可堆叠增益',
    'Stats\n\t\t\t\t\t': '统计\n\t\t\t\t\t',
    'Options\n\t\t\t\t\t': '选项\n\t\t\t\t\t',
    'Sapphire Exponent': '蓝宝石指数',
    'Sapphire Balls': '蓝宝石球',
    'Sapphire Ball Rate': '蓝宝石球几率',
    'Sapphire balls': '蓝宝石球',
    'Ruby balls': '红宝石球',
    'Ruby Balls': '红宝石球',
    'Ruby Ball Rate': '红宝石球几率',
    'Opal Ball': '蛋白石球',
    'Opal balls': '蛋白石球',
    'Opal Balls': '蛋白石球',
    'Opal Ball Rate': '蛋白石球几率',
    'Emerald Ball Rate': '翡翠球几率',
    'Emerald Ball': '翡翠球',
    'Emerald Balls': '翡翠球',
    'Emerald balls': '翡翠球',
    'Auto': '自动',
    'Point Multiplier': '点数倍数',
    'Popup text': '弹出文本',
    'NOTE: Unlocking one gemstone ball sharply increases the cost of unlocking the others!': '注意：解锁一颗宝石球会大幅增加解锁其他宝石球的成本！',
    'Normal Ball': '普通球',
    'Normal Balls': '普通球',
    'New!': '新!',
    'Max Balls': '球上限',
    'Multi-Spin': '批量旋转',
    'Try the beta!': '尝试测试版！',
    'Turquoise Ball': '绿松石球',
    'Turquoise Ball Rate': '绿松石球几率',
    'Turquoise Balls': '绿松石球',
    'Turquoise balls': '绿松石球',
    'Topaz Ball': '黄玉球',
    'Topaz Ball Rate': '黄玉球几率',
    'Topaz Balls': '黄玉球',
    'Topaz balls': '黄玉球',
    'Beach Ball Rate': '沙滩球几率',
    'Beach Ball': '沙滩球',
    'Beach Balls': '沙滩球',
    'Beach balls': '沙滩球',
    'Better Buff Multiplier': '更好的增益倍数',
    'Better Multi-Spin': '更好的批量旋转',
    'Better Point Values': '更好的点数值',
    'Board': '面板',
    'Bonus Wheel': '奖励轮盘',
    'Center Slot Value': '中心槽值',
    'changelog': '更新日志',
    'Click anywhere in the green box to drop a ball.': '点击绿色框中的任意位置以放下球。',
    'Congratulations!': '恭喜你!',
    'Emerald Exponent': '祖母绿指数',
    'Erase save file': '擦除存档文件',
    'Export save file': '导出存档文件',
    'Extra Spin Target': '额外旋转目标',
    'Favicon': '图标',
    'Game loaded': '游戏已加载',
    'Gold Ball': '黄金球',
    'Gold Balls': '黄金球',
    'Gold balls': '黄金球',
    'Gold Ball Value': '黄金球值',
    'Gold Ball Rate': '黄金球几率',
    'Highest buff multiplier': '最高增益倍数',
    'Loading...': '加载中...',
    'manual': '手动',
    'Unlock Amethyst Balls': '解锁紫水晶球',
    'Unlock Beach Balls': '解锁沙滩球',
    'Unlock Emerald Balls': '解锁翡翠球',
    'Unlock Amethyst balls. Amethyst balls have the bonuses of both ruby and sapphire balls.': '解锁紫水晶球。 紫水晶球具有红宝石球和蓝宝石球的优点。',
    'Unlock all 3 of Ruby, Sapphire, and Emerald Balls': '解锁所有 3 个红宝石、蓝宝石和翡翠球',
    'Unlock Emerald balls. Points scored by emerald balls are multiplied by the square of the gold ball multiplier.': '解锁翡翠球。 翡翠球得分乘以金球乘数的平方。',
    'Unlock Gold balls. Gold balls are worth double points and don\'t count towards the max balls limit.': '解锁金球。 金球价值双倍，不计入最大球数限制。',
    'Unlock Opal Balls': '解锁蛋白石球',
    'Unlock Sapphire balls. Sapphire balls are worth the same as a gold ball, plus the gold ball multiplier is also applied to the number of bonus wheel spins earned by sapphire balls."': '解锁蓝宝石球。 蓝宝石球的价值与金球相同，此外，金球乘数也适用于蓝宝石球获得的奖励轮旋转次数。',
    'Unlocked!': '已解锁!',
    'Ruby Ball': '红宝石球',
    'Uses 10% of your available spins at a time, multiplying any points you win from that spin. NOTE: Bonus gold ball drops are not multiplied.': '一次使用 10% 的可用旋转，乘以您从该旋转中赢得的任何积分。 注意：奖金金球掉落不会成倍增加。',
    'Rotation Multiplier': '旋转倍数',
    'Opacity': '透明度',
    'Next upgrade reveal at': '下一步升级显示在',
    'Maximum number of balls allowed on the board at once.': '允许同时在面板上显示的最大球数。',
    'Makes the ruby ball buff stackable. If a ruby ball falls in the center slot while the buff is already active, it extends the duration. Any time over 60 seconds is converted to a multiplier increase. The time extension is inversely proportional to the existing multiplier.': '使红宝石球 增益 可堆叠。 如果红宝石球在 增益 已经激活时落入中心槽，它会延长持续时间。 任何超过 60 秒的时间都会转换为乘数增加。 时间延长与现有乘数成反比。',
    'Auto-Drop': '自动掉落',
    'Auto-Drop Delay': '自动掉落延迟',
    'Auto-Spin': '自动旋转',
    'Automatically drops a ball when allowed. Click in the drop zone to move the drop position.': '在开启的情况下自动丢球。 单击拖放区以移动拖放位置。',
    'Automatically spin the Bonus Wheel.': '自动旋转奖励轮盘。',
    'Game saved': '游戏已保存',
    'Gemstone Balls': '宝石球',
    'Gemstone balls have the benefits of gold balls, plus additional bonuses.': '宝石球具有金球的好处，外加额外的奖励。',
    'Hover over an upgrade to see what it does.': '将鼠标悬停在升级上以查看它的作用。',
    'Import save file': '导入存档',
    'Perhaps just relax and watch the balls drop, if you like.\n\t\t\t': '如果你愿意，也许只是放松一下，看着球落下。\n\t\t\t',
    'Sapphire Ball': '蓝宝石球',
    'since you started playing on this save file.\n\t\t\t\t': '从你开始玩这个存档。\n\t\t\t\t',
    'Time-Based Multiplier': '基于时间的倍数',
    'Topaz Synergy': '黄玉协同作用',
    'Total balls dropped': '落球总数',
    'Total points earned': '总点数',
    'Turquoise Synergy': '绿松石协同作用',
    'Unlock 8-Balls': '解锁 8 球',
    'Back to live version': '返回线上版本',
    'Beach Ball Score Exponent': '沙滩球点数指数',
    'Balls dropped manually': '手动掉落的球',
    'Beach Ball Spin Exponent': '沙滩球旋转指数',
    'Increases point multiplier for gold balls.': '增加金球的点数乘数。',
    'Amethyst Ball': '紫水晶球',
    'Amethyst Ball Rate': '紫水晶球几率',
    'Amethyst Balls': '紫水晶球',
    'Amethyst balls': '紫水晶球',
    'Amethyst Synergy': '紫水晶协同作用',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //树游戏
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme": "主题",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Upgrade levels bought": "已购买的等级升级",
    "Style": "样式",
    "Quality": "质量",
    "Pachinkremental": "弹珠放置",
    "Dark Mode": "深色模式",
    "April Fools": "愚人节",
    "Auto Save": "自动保存",
    "Pop-up text": "弹出文本",
    "Better Ball Drops": "更好的球掉下",
    "Scientific Notation": "科学计数法",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "Hide": "隐藏",
    "Disabled": "已禁用",
    "Enable All": "全部启用",
    'OFF': '关闭',
    'ON': '打开',
    'High': '高',
    'Default': '默认',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+) trillion$/,
    /^([\d\.]+) quadrillion$/,
    /^([\d\.,]+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^All scoring ×(.+) for (.+) seconds!$/, '$2 秒内全部点数 ×$1！'],
    [/^Points earned in last (.+) seconds$/, '过去 $1 秒内获得的点数'],
    [/^Cost: (.+)$/, '成本: $1'],
    [/^Points: (.+)$/, '点数: $1'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);